name: Find and Replace workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Find and Replace
      uses: shitiomatic/str-replace@master
      with:
        find: "\s\sspec.version\s*=\s"\d+.\d+.\d+""
        replace: "  spec.version = "1.1.7.1"
    - name: Commit files # commit the output folder
      run: |
          git config --local user.email "uy.nguyen@wonderlabs.io"
          git config --local user.name "Uy Nguyen"
          git add -A
          git commit -m "Upgrade podspec version"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
          branch: patch-1 #ignore if your branch is master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
